-- This source code was auto-generated by updater.bat

AppStore = {}
AppStore.path = '.'

CatalogInfo = {}
AppInfo = {}

local catalog = nil 
local info = {}

CatalogInfo['10-系统维护'] = {}
catalog = CatalogInfo['10-系统维护']
catalog.name = '10-系统维护'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "cmd"
info.name = "CMD命令行"
info.icon = [[C:\windows\system32\cmd.exe,F]]
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "本地应用"
info.appmode = "runapp"
info.nbapp = "cmd"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = [[%SystemDrive%\windows\system32\cmd.exe]]
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['11-聊天工具'] = {}
catalog = CatalogInfo['11-聊天工具']
catalog.name = '11-聊天工具'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "qq"
info.name = "腾讯QQ"
info.icon = "QQ.ico"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "商店应用(解析)"
info.appmode = "StoreApp_analysis_url"
info.nbapp = "qq"
info.download_page = "https://im.qq.com/pcqq"
info.direct_url = [[https://[^\"]*/qqfile/qq/[^\"]*]]
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\腾讯软件\\QQ\\腾讯QQ.lnk"
info.app_setup_args = "/S"
info.app_setup = "qqsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "wechat"
info.name = "微信电脑版"
info.star = "商店应用"
info.desc = "腾讯出品"
info.icon = "WeChat.ico"
info.download_page = "https://dl.qq.com/wechat"
info.direct_url = "https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe"
info.appmode = "StoreApp_direct_url"
info.nbapp = "wechat"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\微信\\微信.LNK"
info.app_setup_args = "/S"
info.app_setup = "wechatsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['12-影音娱乐'] = {}
catalog = CatalogInfo['12-影音娱乐']
catalog.name = '12-影音娱乐'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "121"
info.name = "kodi"
info.icon = "kodi.png"
info.desc = "I'm Kodi，每一天 乐 - 在 - P - O -R -*"
info.star = "商店应用(解析)"
info.download_page = "https://kodi.tv/download/windows"
info.direct_url = [[https://[^\"]*/releases/windows/win64/kodi[^\"]*]]
info.appmode = "StoreApp_analysis_url"
info.nbapp = "kodi"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Kodi\\Kodi.lnk"
info.app_setup_args = "/S"
info.app_setup = "kodisetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "potplayer"
info.name = "potplayer"
info.icon = "potplayer.png"
info.desc = "I'm Potplayer，每一天 乐 - 在 - * - *"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup.exe"
info.nbapp = "potplayer"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Potplayer\\PotPlayer.lnk"
info.app_setup_args = "/S"
info.app_setup = "potplaysetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "123"
info.name = "vlc播放器"
info.icon = "vlc播放器.png"
info.desc = "I'm QQ，每一天 乐 - 在 - 沟 - 通"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.qq.com/QQ.9.5.6.exe"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vlc"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\VideoLAN\\VLC media player.lnk"
info.app_setup_args = "/S"
info.app_setup = "vlcsetup.exe"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['13-文档办公'] = {}
catalog = CatalogInfo['13-文档办公']
catalog.name = '13-文档办公'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "wps2016"
info.name = "wps2016"
info.icon = "wps.png"
info.desc = "金山出品"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://wdl1.cache.wps.cn/wps/download/W.P.S.7400.12012.0.exe"
info.nbapp = "wps2016"
info.app_runpath = "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\WPS Office\\产品更新信息.lnk"
info.app_setup_args = "/S"
info.app_setup = "wpssetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['14-远程工具'] = {}
catalog = CatalogInfo['14-远程工具']
catalog.name = '14-远程工具'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "Alpemix"
info.name = "Alpemix远程"
info.icon = "Alpemix远程.png"
info.desc = "Alpemix远程是国外的免费远程软件"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://www.alpemix.com/site/Alpemix.exe"
info.nbapp = "Alpemix"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "Alpemix.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "dbadmin"
info.name = "深蓝远程"
info.icon = "Dbadmin.png"
info.desc = "震精网吧界的老牌远程工具，作者一直保证性欲"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "http://down.slser.com/down.php"
info.nbapp = "dbadmin"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "dbadmin.7z"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "oray"
info.name = "向日葵"
info.icon = "向日葵.png"
info.desc = "十几年历史的远程软件"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://api.hanximeng.com/lanzou/?url=https://wwi.lanzouo.com/ihLjvygoxgd&type=down"
info.nbapp = "oray"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "向日葵.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "oraynew"
info.name = "向日葵新版"
info.icon = "向日葵.png"
info.desc = "该版本需要登陆才能使用!"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://sunlogin.oray.com/zh_CN/download/download?id=65&x64=1"
info.nbapp = "oraynew"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "向日葵新版.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "todesk"
info.name = "ToDesk"
info.icon = "todesk.png"
info.desc = "新品远程软件ToDesk完整版"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.todesk.com/windows/ToDesk_Setup.exe"
info.nbapp = "todesk"
info.app_runpath = "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\ToDesk\\ToDesk.lnk"
info.app_setup_args = "/S"
info.app_setup = "todesksetup.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "todesklite"
info.name = "ToDeskLite"
info.icon = "todesk.png"
info.desc = "新品远程软件todesk受控端"
info.star = "商店应用"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.todesk.com/windows/ToDesk_Lite.exe"
info.nbapp = "todesklite"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "todesklite.exe"
info.appmode = "StoreApp_direct_url"
info.user_agent = [[--user-agent="Chrome/94.0.4606.71"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['15-虚拟机类'] = {}
catalog = CatalogInfo['15-虚拟机类']
catalog.name = '15-虚拟机类'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "152"
info.name = "VM16完整版"
info.icon = "vmware.png"
info.desc = "官方完整版vmware"
info.star = "商店应用"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vm16"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://dl.softmgr.qq.com/original/System/VMware-workstation-full-16.1.2-17966106.exe"
info.app_runpath = "temp"
info.app_setup_args = "/S"
info.app_setup = "vmsetup.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]
AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "151"
info.name = "Vmware 16"
info.icon = "vmware.png"
info.desc = "史上最伟大网管精简的vmware虚拟机"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "vmware"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://pan.bilnn.cn/api/v3/file/sourcejump/LWrx2LcM/pIf0htSTViFq5ePgkvFQl-DOKJqF1AVg82xmkGIIoqM*"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "vmware.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['99-更多商店'] = {}
catalog = CatalogInfo['99-更多商店']
catalog.name = '99-更多商店'
catalog.item = {}
catalog.size = 0

info = {} 
info.id = "360softmgr"
info.name = "360软件管家"
info.icon = "360softmgr.png"
info.desc = "360软件管家"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "360softmgr"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://pan.bilnn.cn/api/v3/file/sourcejump/kOgNvkIA/jSJ5yA2yGvrOYpxoGPjr9mgnXD7VBLSHCF9_Qxss6ew*"
info.app_runpath = [["%temp%\\360SoftMgr\\SoftMgr\\SoftMgr.exe"]]
info.app_setup_args = "/S"
info.app_setup = "360softmgr.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

info = {} 
info.id = "qqsoftmgr"
info.name = "QQ软件管理"
info.icon = "qqsoftmgr.png"
info.desc = "QQ软件管理"
info.star = "商店应用(网盘)"
info.appmode = "StoreApp_direct_url"
info.nbapp = "qqsoftmgr"
info.download_page = "https://dl.qq.com"
info.direct_url = "https://pan.bilnn.cn/api/v3/file/sourcejump/mYDNglIw/m_kt3ZBGxm-KmdQl82SAwaTmrtVaBQJU3DwVBI8kbKw*"
info.app_runpath = "temp"
info.app_setup_args = ""
info.app_setup = "qqsoftmgr.exe"
info.user_agent = [[--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36"]]
info.aria2c_args = [[-c -s 2 -x 2 -j 10 --file-allocation=none]]

AppInfo[info.id] = info
catalog.size = catalog.size + 1
catalog.item[catalog.size] = info

CatalogInfo['yy-其他'] = {}
catalog = CatalogInfo['yy-其他']
catalog.name = 'yy-其他'
catalog.item = {}
catalog.size = 0

